apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-pg-depl
spec:
  selector:
    matchLabels:
      app: auth-pg
  template:
    metadata:
      labels:
        app: auth-pg
    spec:
      containers:
        - name: auth-pg
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "auth"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-pg-srv
spec:
  selector:
    app: auth-pg
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
